snapshot-labs/sx.js

src/utils/encoding/index.ts
src/utils/encoding/starknet-execution-params.ts

Added function to encode params for StarkNet execution

starknet execution parameter encoding

---

package.json
src/clients/ethereum-sig/index.ts
src/clients/starknet-sig/index.ts
src/clients/starknet-sig/types.ts
src/utils/encoding/calldata.ts
src/utils/starkkey.ts
test/starkkey.test.ts

Add verify function for StarkKey

---

src/clients/starknet-tx/index.ts
test/index.test.ts

Fix for vote and propose

---

package.json
src/utils/encoding/calldata.ts
src/utils/encoding/slot-key.ts
src/utils/encoding/starknet-commit.ts
src/utils/encoding/starknet-execution-params.ts
src/utils/ints-sequence.ts
src/utils/split-uint256.ts
src/utils/storage-proofs/proof.ts
yarn.lock

* use strings as base data type
* updated package.json

Using strings as base data type rather than bigints (#49)

---

package.json
src/clients/starknet-tx/index.ts
test/index.test.ts
yarn.lock

chore: bump starknet.js to 4.4.2

---

.github/workflows/build-test-release.yml

This should pass, once `GOERLI_NODE_URL` is added as secret in repo settings.

test: add unit tests to Github CI

---

src/types.ts
test/integration/index.test.ts
test/unit/clients/ethereum-sig/__snapshots__/index.test.ts.snap
test/unit/clients/ethereum-sig/index.test.ts

feat: remove executor from vote envelope

---

src/authenticators/index.ts
src/clients/ethereum-sig/types.ts
src/strategies/index.ts
test/integration/index.test.ts
test/unit/authenticators/ethSig.test.ts
test/unit/authenticators/index.test.ts
test/unit/authenticators/vanilla.test.ts
test/unit/clients/ethereum-sig/__snapshots__/index.test.ts.snap
test/unit/clients/ethereum-sig/index.test.ts
test/unit/fixtures.ts
test/unit/strategies/index.test.ts

https://github.com/snapshot-labs/sx-core/blob/35e5401c1c5640008812e355d4fb2ee58405d5a4/deployments/goerli4.json
- Tests pass
- Tested proposal + vote on ethSig + SSP.

feat: upgrade to latest deployment

---

src/authenticators/index.ts
src/strategies/index.ts
src/utils/encoding/eth-sig.ts
src/utils/encoding/index.ts
src/utils/encoding/padding.ts

closes https://github.com/snapshot-labs/sx.js/issues/99

fix: update hex left padding

---

test/integration/index.test.ts

Required after https://github.com/snapshot-labs/sx.js/pull/101

test: update tests to accept starkProvider

---

test/unit/clients/ethereum-sig/index.test.ts

Tests started failing because I create a new proposal and L1 block moved. This mock L1 block for EthereumSig client's tests.
CI passes.

test: mock latest L1 block for EthereumSig

---

package.json

Somehow messed up and added those to regular deps.

chore: move eslint/prettier configs to devDeps

---

package.json

Update to get rid of configs from deps in npm package.

release: v0.1.0-beta.15

---

src/index.ts

It will be used on sx-ui to generate execution data.

chore: export getExecutionData

---

src/clients/zodiac/index.ts
test/integration/zodiac.test.ts

On UI we execute whole proposal and we can do it in one transaction with this method.
- Use UI PR (coming soon).

feat: add executeProposalTxBatch method

---

src/clients/starknet/space-manager/index.ts
test/integration/starknet/spaceManager.test.ts

Depends on https://github.com/snapshot-labs/sx.js/pull/124
This PR adds setMetadataUri call to SpaceManager

feat(starknet): add setMetadataUri to SpaceManager

---

package.json

Release to include EVM support, metadata on Starknet and (if reviewed soon) also Starknet v5 migration (https://github.com/snapshot-labs/sx.js/pull/125).

release: v0.1.0-beta.18

---

src/clients/starknet/space-manager/index.ts
test/integration/starknet/spaceManager.test.ts

Fee estimation fails with ArgentX, we will disable it so it can be handled on the UI.
You should be able to edit space profile using ArgentX on space you control (I can move controller to your account if needed).

feat: add option to disable estimation in SpaceManager

---

src/clients/starknet/space-manager/index.ts
src/networks.ts
src/types/networkConfig.ts
test/integration/starknet/spaceManager.test.ts

This PR adds `deploySpace` method for starknet.
Run
```
STARKNET_ADDRESS=YOUR_ADDRESS STARKNET_PK=YOUR_PK yarn jest -c test/jest.config.integration.js test/integration/starknet/spaceManager.test.ts
```

feat(starknet): add deploySpace method to SpaceManager

---

package.json

This release will allow editing space on UI via ArgentX as well as deploying new spaces (Starknet).
This PR will be merged after this PR gets merged https://github.com/snapshot-labs/sx.js/pull/131

release: v0.1.0-beta.19

---

src/authenticators/starknet/index.ts
test/unit/strategies/index.test.ts

- `yarn lint:nofix` should have no warnings.

chore: remove unused imports

---

src/networks.ts
test/unit/clients/evm/ethereum-sig/__snapshots__/index.test.ts.snap
test/unit/clients/evm/ethereum-sig/index.test.ts

This PR upgrades default network configuration to https://github.com/snapshot-labs/sx-evm/releases/tag/v0.2.0-alpha

feat(evm): upgrade to v0.2.0-alpha

---

package.json

Will be released once this PR is merged: https://github.com/snapshot-labs/sx.js/pull/153
Submitting ahead of time so we can get it released in one round of reviews.

release: v0.1.0-beta.20

---

src/networks.ts
src/strategies/evm/index.ts
src/strategies/evm/whitelist.ts
src/types/networkConfig.ts
test/integration/evm/fixtures/WhitelistStrategy.json
test/integration/evm/index.test.ts
test/integration/evm/utils.ts

Adds whitelist voting strategy support.
Closes: https://github.com/snapshot-labs/sx.js/issues/156
Depends on: https://github.com/snapshot-labs/sx.js/pull/155

feat(evm): add whitelistVotingStrategy support

---

src/clients/evm/ethereum-sig/index.ts
src/clients/evm/ethereum-sig/types.ts
src/clients/starknet/ethereum-sig/index.ts
src/clients/starknet/ethereum-sig/types.ts
src/networks.ts
src/types/networkConfig.ts
test/integration/evm/utils.ts
test/unit/clients/evm/ethereum-sig/__snapshots__/index.test.ts.snap

This PR adds mana support by exposing `send` method to ping mana as well as making EIP712 chainId customizable.

feat: add mana support

---

src/clients/evm/ethereum-tx/index.ts
test/integration/evm/utils.ts

This param will be used to format voting power on the UI.

feat(evm): accept voting strategies metadata

---

package.json

To be merged after: https://github.com/snapshot-labs/sx.js/pull/178

release: v0.1.0-beta.25

---

src/clients/evm/ethereum-sig/index.ts
src/networks.ts
test/unit/clients/evm/ethereum-sig/__snapshots__/index.test.ts.snap
test/unit/clients/evm/ethereum-sig/index.test.ts

feat: upgrade contracts to v0.4.0

---

package.json

To be merged after https://github.com/snapshot-labs/sx.js/pull/183

release: v0.1.0-beta.26

---

package.json

This release includes timelock support.

release: v0.1.0-beta.27

---

src/authenticators/evm/ethSig.ts
src/authenticators/evm/ethTx.ts
src/authenticators/evm/vanilla.ts
src/clients/evm/ethereum-sig/index.ts
src/clients/evm/ethereum-sig/types.ts
src/clients/evm/ethereum-tx/index.ts
src/clients/evm/types.ts
test/unit/clients/evm/ethereum-sig/__snapshots__/index.test.ts.snap
test/unit/clients/evm/ethereum-sig/index.test.ts

This PR adds support for `updateProposal` method.

feat: add updateProposal method

---

src/networks.ts

You can test with UI (PR coming).

feat: add v0.5.0 contracts

---

src/clients/evm/ethereum-tx/index.ts

When scheduling transactions with WalletConnect and Safe it never resolves so we have to have a way to finish execution.

feat: add noWait option

---

src/clients/evm/ethereum-sig/index.ts
src/networks.ts

https://github.com/snapshot-labs/sx-evm/blob/refactor_deployments/deployments/linea.json

feat: add linea testnet support

---

src/clients/evm/ethereum-sig/index.ts
src/clients/evm/ethereum-tx/index.ts
src/networks.ts

This PR add support for Polygon and Arbitrum, do you see anything missing?
Also remove some unused import and update Mana URL to `https://mana.pizza`

feat: add support for Polygon and Arbitrum

---

src/clients/evm/ethereum-sig/index.ts
src/clients/evm/ethereum-sig/types.ts
src/clients/evm/types.ts
test/unit/clients/evm/ethereum-sig/__snapshots__/index.test.ts.snap

For: https://github.com/snapshot-labs/sx-ui/issues/735

fix(evm): add salt to updateProposal message

---

package.json

To be released once this is merged:
- https://github.com/snapshot-labs/sx.js/pull/214

release: v0.1.0-beta.39

---

src/clients/evm/ethereum-sig/index.ts
src/clients/evm/ethereum-tx/index.ts
src/clients/starknet/ethereum-sig/index.ts
src/clients/starknet/ethereum-tx/index.ts
src/clients/starknet/starknet-sig/index.ts
src/clients/starknet/starknet-tx/index.ts
src/networks.ts
src/strategies/evm/index.ts
src/utils/strategies.ts

- Accept strategies that throw when building params (for example when using merkle white list).
- Starknet `updateSettings` fixes.
- EVM `updateSettings` fixes.

feat: updateSettings fixes

---

package.json
src/utils/encoding/starknet-execution-params.ts
test/unit/strategies/starknet/erc20Votes.test.ts
yarn.lock

Depends on https://github.com/snapshot-labs/sx.js/pull/232

chore: update to latest eslint/prettier configs

---

src/clients/evm/types.ts
src/clients/index.ts
src/clients/starknet/herodotus/index.ts
src/networks.ts
src/strategies/evm/comp.ts
src/strategies/evm/merkleWhitelist.ts
src/strategies/evm/ozVotes.ts
src/strategies/starknet/abis/EVMSlotValue.json
src/strategies/starknet/erc20Votes.ts
src/strategies/starknet/evmSlotValue.ts
src/strategies/starknet/index.ts
src/strategies/starknet/merkleWhitelist.ts
src/strategies/starknet/vanilla.ts
src/types/index.ts
src/types/networkConfig.ts
src/utils/strategies.ts
test/unit/strategies/evm/comp.test.ts
test/unit/strategies/evm/ozVotes.test.ts
test/unit/strategies/evm/vanilla.test.ts
test/unit/strategies/starknet/erc20Votes.test.ts
test/unit/strategies/starknet/merkleWhitelist.test.ts
test/unit/strategies/starknet/vanilla.test.ts

This PR adds support for evmSlotValue strategy and HerodotusController (used on mana for caching timestamps).

feat: add evmSlotValue support

---

src/strategies/starknet/evmSlotValue.ts

We fetch live storage from L1 to compute current voting power.

feat: calculate current voting power

---

package.json
src/clients/starknet/starknet-tx/index.ts
src/networks.ts
test/unit/authenticators/starknet/index.test.ts
test/unit/clients/starknet/ethereum-sig/__snapshots__/index.test.ts.snap
test/unit/clients/starknet/ethereum-sig/index.test.ts
test/unit/clients/starknet/ethereum-tx/index.test.ts
test/unit/clients/starknet/starknet-sig/__snapshots__/index.test.ts.snap
test/unit/clients/starknet/starknet-sig/index.test.ts
test/unit/strategies/starknet/index.test.ts
yarn.lock

This PR adds support for Sepolia network, moves configuration to single place (just for Starknet for now) and fixes bug caused by nonce management when using Starknet.
- Test with this UI PR: XYZ

chore(starknet): add sepolia network

---

src/networks.ts

https://github.com/snapshot-labs/sx-evm/releases/tag/v1.0.3

chore(evm): use v1.0.3 deployment for mainnet
