snapshot-labs/sx.js

src/utils/encoding/starknet-execution-params.ts
Small fix to the encoding such that it matches the OZ and Argent account standard for a call: 
```
struct AccountCallArray:
member to: felt
member selector: felt
member data_offset: felt
member data_len: felt
end
```
Previously, the `data_offset` and `data_len` were switched. 
Also renamed the transaction type from `StarknetMetaTransaction` to `Call` to maintain naming consistency with OZ and Argent.
=> updated starknet execution params encoding

src/utils/encoding/calldata.ts, src/utils/ints-sequence.ts
- Update `getProposeCalldata`
- Add `LEFromString` which creates an `IntsSequence` in `LE` from a `string` (e.g `0x112233445566778899` -> `[0x8877665544332211, 0x99]`
=> Add support for string in eip712

src/clients/starknet-tx/constants.json, src/clients/starknet-tx/index.ts, test/index.test.ts
This PR switches to use latest deployment of spaces, with different types of auth/strategy combos set in config so it's easier to switch to particular one.
=> feat: use latest deployment contracts

jest.config.js, test/index.test.ts
Closes #71 
Configure [`extraGlobals`](https://jestjs.io/docs/configuration#sandboxinjectedglobals-arraystring)
- Run test of your choice.
- It should run faster than it used to be (was able to lower timeouts to 60s, and that should have headroom anyway).
=> test: set extraGlobals to speedup jest Math

.eslintrc, jest.config.js, package.json, src/clients/starknet-tx/index.ts, test/integration/index.test.ts, test/jest.config.base.js, test/jest.config.integration.js, test/jest.config.unit.js, test/unit/clients/starknet-tx/__snapshots__/index.test.ts.snap, test/unit/clients/starknet-tx/index.test.ts, test/unit/utils/starkkey.test.ts
Split tests into `unit` and `integration` tests.
This way we can run easy to test code automatically, and stuff that isn't fully automated yet (new proposals on the network) can still be executed manually.
In the future PR I will update Github to run unit tests in CI. (we will need to have `GOERLI_NODE_URL` added as a secret).
- Run `GOERLI_NODE_URL="XXX" yarn test` 
- Run `GOERLI_NODE_URL="XXX" ETH_PK="YYY" yarn test:integration` with your test selected by `.only`.
=> test: separete unit and integration tests

src/authenticators/ethSig.ts, src/authenticators/index.ts, src/authenticators/vanilla.ts, src/clients/starknet-tx/constants.ts, src/clients/starknet-tx/contracts.ts, src/clients/starknet-tx/index.ts, src/types.ts, test/unit/authenticators/ethSig.test.ts, test/unit/authenticators/fixtures.ts, test/unit/authenticators/index.test.ts, test/unit/authenticators/vanilla.test.ts
Creates `Authenticator` interface that StarknetTx client uses to build call for propose/vote methods.
Right now authenticators are simple objects (instead of classes) as they shouldn't need internal state so this way it's cleaner, but we can see how it scales and change it if needed - as it's already an interface it won't be hard to migrate.
- Tests pass.
- Try creating proposal (or voting) with vanilla + ethSig authenticators (same as before, by using `.only` in test:integration).
=> refactor: make authenticators pluggable

src/clients/starknet-tx/index.ts, src/strategies/singleSlotProof.ts, src/strategies/vanilla.ts, src/types.ts, src/utils/encoding/index.ts, src/utils/encoding/storage-vars.ts, test/unit/strategies/singleSlotProof.test.ts, test/unit/strategies/vanilla.test.ts, test/unit/utils/encoding/storage-vars.test.ts
Instead of using hardcoded strategy params (that we use to fetch correct proofs) they are now fetched from the network.
Block is hardcoded still, as in current state we 
- Create proposal with SSP.
=> feat: fetch strategy params from network

src/clients/starknet-tx/index.ts, src/utils/encoding/calldata.ts
`.toString(16)` return value was missing `0x` prefix and it was failing when going to 10 and above.
Made `getVoteCalldata` accept number, similar to choice and make it encode it internally.
=> fix: encode proposalID with 0x prefix

test/unit/strategies/singleSlotProof.test.ts
Makes tests deterministic by mocking latestL1Block so it always gets the same results no matter the network state.
- Tests should pass.
=> test: make unit tests deterministic

package.json
Bumping version so we can release it and use it in mana/sx-ui.
=> chore: bump version to 0.1.0-beta.13

src/clients/ethereum-sig/index.ts, src/clients/starknet-tx/index.ts, src/strategies/singleSlotProof.ts, src/types.ts, test/unit/clients/ethereum-sig/index.test.ts, test/unit/strategies/singleSlotProof.test.ts, test/unit/strategies/vanilla.test.ts
Updated the `ClientConfig` object to include a starknet provider. We then use this provider instead of the default one. 
closes https://github.com/snapshot-labs/sx.js/issues/97
=> added starknet provider to client config

src/authenticators/index.ts, src/strategies/index.ts, test/unit/authenticators/index.test.ts, test/unit/strategies/index.test.ts
we add a default to the `getStrategy` and `getAuthenticator` functions, but users are able to specify an alternative object. No breaking change
closes https://github.com/snapshot-labs/sx.js/issues/98
=> added default strategies and authenticators

src/executors/ethRelayer.ts, src/executors/index.ts, src/executors/starknet.ts, src/executors/vanilla.ts, src/types.ts, src/utils/encoding/starknet-execution-params.ts, test/integration/index.test.ts, test/unit/executors/ethRelayer.test.ts, test/unit/executors/index.test.ts, test/unit/executors/starknet.test.ts, test/unit/executors/vanilla.test.ts
Closes: https://github.com/snapshot-labs/sx.js/issues/95
Closes: https://github.com/snapshot-labs/sx.js/issues/96 (probably, because Starknet execution doesn't use execution hash)
This PR adds Executor classes that can be used to generate execution data for different types of executors (EthRelayer, Vanilla, Starknet).
- `Vanilla` - empty params
- `EthRelayer` - hash of transactions and L1 destination
- `Starknet` - encoded calls
`Starknet` executor doesn't use executionHash (it encodes whole calls), so it's impossible to abstract all of them to use single executionHash. What those executors accept as params are also different (for example EthRelayer takes txs, L1 destination and chainId while Starknet takes just calls) so it's hard to make it hands-off experience for the user, but it's …
=> feat: add executors

test/integration/index.test.ts
Previous goerli2 testnet was deployed with bug that made it use goerli1 chainId, but it was changed today to use its own chainId.
`starknet` doesn't derive it properly from network so it needs to be set explicitly along the URL.
=> fix: set chainId on starkProvider

src/index.ts
This way we won't need to drill files from `dist`.
=> chore: export networks and types

src/authenticators/ethSig.ts, src/authenticators/index.ts, src/clients/ethereum-sig/index.ts, src/clients/starknet-tx/index.ts, src/clients/zodiac/index.ts, src/executors/ethRelayer.ts, src/executors/starknet.ts, src/strategies/index.ts, src/strategies/singleSlotProof.ts, src/types/index.ts, src/utils/strategies.ts
Because of import cycles production build of sx-ui is currently broken because Vite can't build the tree properly (right now you can't propose on testnet.snapshotx.xyz). This PR removes import cycles by stopping global `utils` import to solve this issue.
Run:
```bash
madge --circular --ts-config ./tsconfig.json --extensions ts ./src/
```
No circular dependencies should be found.
=> refactor: remove import cycles

package.json, src/clients/zodiac/index.ts, test/integration/spaceManager.test.ts, test/integration/zodiac.test.ts
Depends on https://github.com/snapshot-labs/sx.js/pull/118
Wallet is too complex to require, we can do with just signer.
=> refactor: accept Signer instead of Wallet

package.json, src/utils/encoding/storage-vars.ts, src/utils/starkkey.ts, test/integration/starknet/index.test.ts, test/jest.config.base.js, test/unit/clients/ethereum-sig/__snapshots__/index.test.ts.snap, test/unit/strategies/__snapshots__/singleSlotProof.test.ts.snap, test/unit/utils/starkkey.test.ts, tsconfig.json, yarn.lock
Closes https://github.com/snapshot-labs/sx.js/issues/122
starknet v5 is still in beta, but is way faster at computing hashes.
Test with sx-ui or with tests.
https://github.com/snapshot-labs/sx-ui/pull/397
=> feat: upgrade to starknet v5

src/clients/starknet/space-manager/index.ts
BigInt can't get serialized by ArgentX
Missed this and it won't work in web.
=> fix(starknet): serialize metadataUri

src/authenticators/evm/ethSig.ts
`toHex()` can lose padding, we need to padd it for ethers.js.
Closes: https://github.com/snapshot-labs/sx.js/pull/new/sekhmet/hex-pad-rsv
- Run `yarn anvil`
- Run `yarn test:integration:evm` couple times, it always passes.
=> fix(evm): add left pad to RSV

src/clients/evm/ethereum-tx/index.ts, test/integration/evm/index.test.ts, test/integration/evm/utils.ts
This PR unified deploySpace call a bit more to starknet one (only difference is votingStrategies format).
- rename `deploy` to `deploySpace`.
- use `bigint` for `quorum` and `proposalThreshold`.
- use `spaceFactory` from networkConfig.
=> refactor(evm): unify deploySpace call

package.json, test/integration/starknet/index.test.ts, test/integration/starknet/spaceManager.test.ts, yarn.lock
New version got released and I can't upgrade Mana because it tries to install 5.0.0 that has different types.
Using hardcoded version as 5.0.0 and 5.0.1 are incompatible with each other too.
=> chore: use stable starknet@v5

package.json, test/integration/starknet/index.test.ts, test/integration/starknet/spaceManager.test.ts, yarn.lock
Depends on https://github.com/snapshot-labs/sx.js/pull/167
I will need yet another release later, but without official release yarn installs bad version of starknet and it's impossible to test Mana.
=> release: v0.1.0-beta.22

src/clients/evm/ethereum-tx/index.ts, test/integration/evm/index.test.ts
Closes https://github.com/snapshot-labs/sx.js/issues/172
Currently Mana sets its own address as voter/proposer, causing those actions to fail, if you are not me.
Now it will read it from signatureData if available.
- Run `yarn anvil`.
- Run `yarn test:integration:evm`.
=> fix(evm): use correct propser/voter address

src/strategies/evm/abis/IComp.json, src/strategies/evm/comp.ts
Closes: https://github.com/snapshot-labs/sx.js/issues/171
getPriorVotes sometimes fail with latest block with error not determined yet.
We can call getCurrentVotes instead, saving one request and preventing those race conditions
=> fix(evm): use getCurrentVotes if stored block is missing

package.json
Release with `@ethereumjs` packages removed.
=> release: v0.1.0-beta.28

src/strategies/starknet/erc20Votes.ts, test/unit/strategies/starknet/erc20Votes.test.ts
It will fail on contract side if used. Throwing there will prevent it from being used when voting/proposing.
=> fix: do not use erc20Votes strat on ETH addresses

.gitignore, package.json, tsconfig.cjs.json, tsconfig.json
If we ship ESM Vite can use this package directly without pre-bundling. This makes Vite reload on changes in this linked package (useful in mono repo, but outside of it as well).
=> feat: enable ESM builds

.gitignore, package.json, tsconfig.cjs.json, tsconfig.json
Depends on https://github.com/snapshot-labs/sx.js/pull/228
This option is not needed currently, but once moved to mono repo we will encounter some broken types from sx-ui (@types/remarkable and @type/inquirer).
Until those are fixed we will need this. I will see if I can resolve those upstream later.
=> chore: set skipLibCheck to true

src/utils/starknet-enums.ts
the enum variants need to be defined in the same order as in Cairo in order for the encoding to be correct.  Cairo definition: https://github.com/snapshot-labs/sx-starknet/blob/49e42850c808fea30e9fb5da5408478fee7ac680/starknet/src/types/user_address.cairo#L6C1-L6C1
=> fix: user address enum order

test/unit/strategies/starknet/erc20Votes.test.ts
Using same node as checkpoint-template. Had to use goerli1 deployment.
=> test: update erc20votes tests to use different provider

src/clients/evm/types.ts, src/networks.ts, src/strategies/evm/comp.ts, src/strategies/evm/merkleWhitelist.ts, src/strategies/evm/ozVotes.ts, src/strategies/starknet/erc20Votes.ts, src/strategies/starknet/evmSlotValue.ts, src/strategies/starknet/merkleWhitelist.ts, src/types/index.ts, src/types/networkConfig.ts, test/unit/strategies/evm/comp.test.ts, test/unit/strategies/evm/ozVotes.test.ts, test/unit/strategies/evm/vanilla.test.ts, test/unit/strategies/starknet/erc20Votes.test.ts, test/unit/strategies/starknet/merkleWhitelist.test.ts, test/unit/strategies/starknet/vanilla.test.ts
Changes:
- uses predefined chainId for herodotus (it's no longer part of metadata).
- uses real timestamp instead of reading hardcoded proposal ID (for some reason it got commited like this).
=> fix: use proper start timestamp and chainId

src/clients/starknet/starknet-tx/index.ts
This allows us to provide nonce to `propose`/`updateProposal`/`vote` calls. I wanted to use special `Account` type for it, but reverting nonce wasn't really possible with the way `getNonce` is called.
We also have to separate estimateFee call as it won't work with nonces in the future (technically it might be estimating fee at wrong block because of it, but hopefully it doesn't matter that much - we can't do much about it).
=> feat: accept providedNonce
